### ISSUE TITLE
Error: Path is not a directory

### ISSUE THREAD

**Issue by ch40s** [compoterhacker/mehrai#1]
This path/directory (/var/lib/docker/devicemapper/mnt/) actually exists on my host so I don't know why I get this error:

```
File "mehrai.py", line 52, in run
    observer.schedule(FileHandler(), path='/var/lib/docker/devicemapper/mnt/' + dockerid + '/rootfs', recursive=recurse)
...
  File "/usr/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 380, in _add_dir_watch
    raise OSError('Path is not a directory')
```

**Comment by compoterhacker** [comment]
is the untruncated container ID in there? are you running it as root?

**Comment by ch40s** [comment]
I tried as user member of the docker group and as root.
The container ID is not a directory under /var/lib/docker/devicemapper/mnt/ but under /var/run/docker/libcontainerd/ .

**Comment by compoterhacker** [comment]
Word yeah and that worked? The folder depends on distro and docker version, I've seen a few different ones. Feel free to hack it til it works.

**Comment by ch40s** [comment]
So, "docker ps -l --no-trunc | grep 'mehrai' | awk '{print $1}' "gives me an ID which exists under "/var/lib/docker/containers/". That directory includes hostconfig.json, resolv.conf, hosts, etc.

Under "/var/lib/docker/devicemapper/mnt/" there is a different ID which has the rootfs directory inside.

Both paths give me the same error. Based on the description above, do I have to use the first or the second path?

**Comment by compoterhacker** [comment]
The first directory is not correct. The second contains different docker containers rootfs' if yours isn't there. Have you tried /var/lib/docker/aufs/mnt? That seems to be a common one myself and others have run into.

In this case, you will have to patch the code at line 55 to:
`
observer.schedule(FileHandler(), path='/var/lib/docker/aufs/mnt/' + dockerid, recursive=recurse)
`
Note the lack of the 'rootfs' at the end of the path, because some docker verisons don't have it.

I'll pin these kind of things down in a later, fully realized version, but I just don't have time at the moment.

**Comment by ch40s** [comment]
It worked after changing the path to "/var/lib/docker/image/devicemapper/layerdb/mounts/" and removed '/rootfs'. Thanks a lot! ;)

**Comment by ch40s** [comment]
Update: the correct path was "/var/lib/docker/devicemapper/mnt/" which includes /rootfs.
Keep in mind that the command "docker ps -l --no-trunc | grep 'mehrai' | awk '{print $1}'" might return the wrong id.
